apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: inventory-service
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  POSTGRES_DB: "inventorydb"
  POSTGRES_USER: "postgres"
