services:
  inventoryservice:
    build: .
    container_name: inventoryservice
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db-inventory;Database=inventorydb;Username=postgres;Password=postgres
    depends_on:
      db-inventory:
        condition: service_healthy

  db-inventory:
    image: postgres:16
    container_name: db-inventory
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventorydb
    volumes:
      - inventory_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventorydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  inventory_data:
